BASE_TASK_CONFIG_PATH: "configs/tasks/objectnav_mp3d.yaml"
TRAINER_NAME: "uncertain-q"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 1
DATA_ACCUMULATION: 1
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "tb/train"
VIDEO_DIR: "data_ssd/video_dir"
TEST_EPISODE_COUNT: 2184
EVAL_CKPT_PATH_DIR: "model_checkpoints"
NUM_PROCESSES: 16
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR"]
CHECKPOINT_FOLDER: "cpt"
NUM_UPDATES: 10000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 250

RL:
  SUCCESS_REWARD: 10.0
  SLACK_REWARD: -0.01
  DQN:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 2
    num_mini_batch: 6
    weight_decay: 1.0e-3
    value_loss_coef: 0.5
    entropy_coef: 1.0e-4
    ### Adjust the discount, learning rates, replay buffer size
    discount: 0.95
    lr: 2.5e-4
    eps: 1.0e-7
    replay_buffer_size: 128
    max_grad_norm: 0.2
    num_steps: 128
    num_local_steps: 16
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 50
    use_normalized_advantage: False
    hidden_size: 512
    num_mc_drop: 4 # number of MC-Dropout model 
    mc_drop_rate: 0.5
    num_classes: 23
    confidence_rate: 1.2
    semantic_pretrain: './segmentation_ckp/mobilenet_habitat_best_model.pth'
  MAPS:
    egocentric_map_size: 100 # 10m depth range for 
    global_map_size: 400 # 40m range global map coverage
    coordinate_min: -20.0
    coordinate_max:  20.0
    vacant_belief: -450
    occupied_belief: 100
    entropy_coef: 5.0e-2

