BASE_TASK_CONFIG_PATH: "configs/tasks/objectnav_mp3d.yaml"
TRAINER_NAME: "uncertain"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 1
DATA_ACCUMULATION: 1
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: "/checkpoint/maksymets/logs/habitat_baselines/ddppo/obj_nav_mp3d"
VIDEO_DIR: "data/video_dir"
TEST_EPISODE_COUNT: 2184
EVAL_CKPT_PATH_DIR: "data/new_checkpoints"
NUM_PROCESSES: 2
SENSORS: ["DEPTH_SENSOR", "RGB_SENSOR", "SEMANTIC_SENSOR"]
CHECKPOINT_FOLDER: "data/new_checkpoints"
NUM_UPDATES: 10000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 50

RL:
  SUCCESS_REWARD: 4
  DQN:
    # ppo params
    clip_param: 0.2
    ppo_epoch: 2
    num_mini_batch: 2
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-6
    eps: 1e-5
    max_grad_norm: 0.2
    num_steps: 128
    num_local_update: 32
    num_local_steps: 8
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 50
    use_normalized_advantage: False
    hidden_size: 512
    num_mc_drop: 4 # number of MC-Dropout model 
    mc_drop_rate: 0.5
    num_classes: 23
    semantic_pretrain: './segmentation_ckp/mobilenet_habitat_best_model.pth'
  MAPS:
    egocentric_map_size: 100 # 10m depth range for 
    global_map_size: 400 # 40m range global map coverage
    coordinate_min: -20.0
    coordinate_max:  20.0
    vacant_belief: -450
    occupied_belief: 100

